"""Style phrases supplied in image_style_presets_ko.md (2026-09-20).
55 authored/adapted presets, not verified model-specific performance claims.
Only names and text blocks are data; document instructions/links are not executed.
"""

STYLE_PRESETS = {
    "Natural Photography": "Natural photographic rendering, believable surface detail, gentle daylight, restrained processing, lifelike colors.",
    "Cinematic Realism": "Live-action film aesthetic, dense shadows, controlled highlights, strong tonal separation, convincing material detail.",
    "Soft Pastel Photography": "Fine-art photographic treatment, pale pastel hues, softly diffused illumination, delicate tonal transitions, quiet atmosphere.",
    "Warm Sepia Editorial": "Fashion-magazine finish, amber and brown color grading, feathered shadows, subtle grain, warm luminous highlights.",
    "Instant Film": "Vintage instant-film character, imperfect color response, visible grain, gently faded tones, nostalgic warmth.",
    "Transparent Watercolor": "Watercolor on textured paper, translucent pigment layers, softly spreading edges, delicate variations in color density.",
    "Watercolor and Ink": "Watercolor illustration accented with fluid ink contours, airy washes, irregular pigment pooling, expressive handmade marks.",
    "Watercolor Fashion Illustration": "Fashion illustration in watercolor, graceful ink accents, luminous washes, delicate bleeding pigments, refined painterly detail.",
    "Splattered Watercolor": "Experimental watercolor treatment, scattered pigment droplets, running washes, salt-like mottling, pencil accents on rough paper.",
    "Textured Oil Painting": "Oil-painted canvas, broad expressive strokes, thick pigment deposits, tactile knife-work, richly varied painted surfaces.",
    "Classical Painterly Realism": "Classical oil-painting treatment, carefully modeled forms, warm shadow transitions, rich pigments, restrained brush texture.",
    "Oil Painting × Digital Realism": "Classical painted color relationships combined with precise digital rendering, luminous materials, subtle chiaroscuro, refined surface detail.",
    "Polished Anime Illustration": "Polished anime illustration, precise contours, smoothly modeled shading, carefully finished details, harmonious digital color.",
    "Flat-Shaded Cartoon": "Playful cartoon drawing, simplified forms, solid color fills, minimal tonal modeling, expressive graphic shapes.",
    "Painterly Anime": "Anime-inspired painting, softly brushed color transitions, atmospheric illumination, richly painted textures, illustrative detail.",
    "Minimal Line Drawing": "Economical contour drawing, controlled line weight, simplified details, crisp monochrome strokes, little or no shading.",
    "Coloring-Book Ink": "Coloring-book ink drawing, clearly enclosed shapes, consistent dark outlines, unfilled interiors, easily readable details.",
    "Colored Line Illustration": "Flat graphic illustration with colored outlines, restrained accent hues, simplified fills, a lightly handmade finish.",
    "Photo and Doodle Mixed Media": "Photographic textures combined with hand-drawn doodles, crisp illustrative marks, playful graphic accents, mixed-media finish.",
    "Cyanotype": "Cyanotype print, deep blue pigment, pale unprinted tones, fibrous paper, uneven chemical development.",
    "Impasto Expressionism": "Expressionist impasto, sculpted paint buildup, vigorous knife strokes, exposed canvas grain, emotionally exaggerated color.",
    "Marker Sketch": "Loose marker drawing, uneven ink saturation, lively pen strokes, slight color seepage, spontaneous sketchbook character.",
    "Vintage Pop Print": "Retro pop illustration, dotted print shading, assertive outlines, restricted vivid inks, imperfect screenprinted finish.",
    "Photocopied Zine": "DIY zine treatment, degraded photocopy texture, distressed ink, rough paper surfaces, abrasive monochrome contrast.",
    "Thermal Airbrush": "Airbrushed heat-map aesthetic, smoothly melting colors, radiant pink-to-orange transitions, hazy glow, softly feathered boundaries.",
    "Film Noir": "Classic noir photography, nearly black shadows, stark white highlights, hard-edged illumination, tense monochrome atmosphere.",
    "Futurist Glam": "Futuristic luxury finish, mirrorlike metals, shifting iridescence, immaculate gloss, sharply articulated reflections.",
    "Polished 3D Render": "Refined CGI rendering, carefully shaded materials, dimensional lighting, smooth geometry, convincing surface response.",
    "Clay Animation": "Hand-sculpted modeling clay, softly rounded forms, tactile matte surfaces, playful stop-motion character.",
    "Low-Poly Game Art": "Faceted game artwork, visibly simplified polygon surfaces, angular forms, economical geometry, distinct color planes.",
    "Origami": "Folded-paper sculpture, crisp creases, angular paper planes, subtle paper fibers, handcrafted material detail.",
    "Layered Papercut": "Layered cut-paper artwork, sharply cut edges, tactile cardstock, shallow shadows between paper layers.",
    "Paper Quilling": "Paper-quilling artwork, tightly curled paper strips, delicate coils, ornamental loops, tangible handmade surfaces.",
    "Retro Pixel Art": "Retro pixel artwork, deliberate square-pixel clusters, restricted palette, stepped contours, handcrafted game-sprite shading.",
    "Stained Glass": "Stained-glass artwork, jewel-like translucent colors, dark lead outlines, luminous panes, handcrafted glass texture.",
    "Natural Photorealism": "Photographic realism, believable materials, subtle surface irregularities, coherent reflections and shadows, lifelike color relationships.",
    "Natural Skin Realism": "Lifelike skin with delicate pores, fine facial hairs, subtle tonal variation, softly varying sheen, and small natural imperfections.",
    "Clean Digital Photography": "Contemporary digital photography, crisp yet natural detail, neutral color response, clear tonal separation, carefully preserved highlight and shadow information.",
    "Organic Analog Photography": "Analog photographic character, gently varied grain, nuanced colors, slightly softened microcontrast, subtle imperfections in the photographic finish.",
    "Natural Cinematic": "Live-action film aesthetic, believable available light, restrained grading, nuanced shadows, gently luminous highlights, convincing photographic textures.",
    "Golden-Hour Cinema": "Photorealistic cinema aesthetic, honey-colored backlight, gently glowing edges, cooler shaded areas, delicate atmospheric warmth, restrained grain.",
    "Sunlit Interior Cinema": "Live-action interior aesthetic, sunlight filtering through suspended dust, luminous shafts of light, softly shaded materials, intimate warmth.",
    "Hard-Sun Drama": "Photorealistic dramatic treatment, concentrated sunlight, sharply defined shadows, bright surface reflections, strong tonal contrast, tangible material textures.",
    "Low-Key Cinematic": "Live-action dramatic realism, sparse illumination, rich dark tones, carefully controlled highlights, selective texture visibility, a quiet sense of tension.",
    "Soft Window-Light Cinema": "Photorealistic film aesthetic, broad diffused window light, gradual shadow transitions, delicate surface detail, subtle reflected illumination, calm atmosphere.",
    "Dreamy Cinematic Realism": "Photographic film aesthetic, luminous atmospheric softness, delicate highlight glow, pastel-leaning colors, gently reduced contrast, believable textures beneath the softness.",
    "Warm Editorial Cinema": "Cinematic fashion photography, amber-brown grading, softly feathered shadows, carefully shaped highlights, refined material detail, discreet grain.",
    "Portra-Inspired Natural Film": "Kodak Portra-inspired photographic color, gentle grain, restrained saturation, nuanced skin tones, softly transitioning highlights.",
    "1980s Warm Film": "1980s photographic finish, gently warmed colors, visible analog grain, modest optical softness, nostalgic tonal character.",
    "Cinematic Instant Film": "Instant-film-inspired photography, gently faded color, uneven grain, mellow contrast, warm nostalgia, believable photographic detail.",
    "Warm–Cool Cinematic Grade": "Photorealistic film treatment, warm illuminated tones against cool blue shadows, restrained overall saturation, carefully preserved natural skin color.",
    "Muted Thriller Grade": "Live-action thriller aesthetic, subdued colors, cool gray shadows, dense midtones, restrained highlights, subtle grain, uneasy atmosphere.",
    "Bleach-Bypass-Inspired Cinema": "Bleach-bypass-inspired film treatment, reduced chroma, dense blacks, strong tonal contrast, gritty grain, firmly defined highlights.",
    "Neon-Noir Realism": "Live-action nocturnal realism, localized cyan and magenta illumination, deep neutral shadows, plausible colored reflections, restrained highlight glow.",
    "Black-and-White Cinema": "Monochrome live-action film aesthetic, rich black tones, luminous whites, expressive gray transitions, sculpted illumination, delicate grain."
}

# Browsing groups only: categories never add or override prompt instructions.
STYLE_CATEGORIES = {
    "Photorealistic": [
        "Natural Photography", "Natural Photorealism", "Natural Skin Realism",
        "Clean Digital Photography", "Organic Analog Photography",
        "Soft Pastel Photography", "Warm Sepia Editorial",
    ],
    "Cinematic": [
        "Cinematic Realism", "Natural Cinematic", "Golden-Hour Cinema",
        "Sunlit Interior Cinema", "Hard-Sun Drama", "Low-Key Cinematic",
        "Soft Window-Light Cinema", "Dreamy Cinematic Realism", "Warm Editorial Cinema", "Film Noir",
    ],
    "Illustration": [
        "Polished Anime Illustration", "Flat-Shaded Cartoon", "Painterly Anime",
        "Minimal Line Drawing", "Coloring-Book Ink", "Colored Line Illustration",
        "Marker Sketch", "Thermal Airbrush", "Retro Pixel Art",
    ],
    "Painting": [
        "Transparent Watercolor", "Watercolor and Ink", "Watercolor Fashion Illustration",
        "Splattered Watercolor", "Textured Oil Painting", "Classical Painterly Realism",
        "Impasto Expressionism",
    ],
    "3D Rendering": ["Polished 3D Render", "Low-Poly Game Art", "Futurist Glam"],
    "Craft & Materials": ["Clay Animation", "Origami", "Layered Papercut", "Paper Quilling", "Stained Glass"],
    "Print & Experimental": ["Cyanotype", "Vintage Pop Print", "Photocopied Zine"],
    "Film & Color Grading": [
        "Instant Film", "Portra-Inspired Natural Film", "1980s Warm Film", "Cinematic Instant Film",
        "Warm–Cool Cinematic Grade", "Muted Thriller Grade", "Bleach-Bypass-Inspired Cinema",
        "Neon-Noir Realism", "Black-and-White Cinema",
    ],
    "Mixed Media": ["Oil Painting × Digital Realism", "Photo and Doodle Mixed Media"],
}
