"""Style phrases supplied in image_style_presets_ko (3).md (2026-09-23).
115 authored/adapted presets, not verified model-specific performance claims.
Only names and text blocks are data; document instructions/links are not executed.
"""

STYLE_PRESETS = {
    "Natural Photography": "Natural photographic rendering, believable surface detail, gentle daylight, restrained processing, lifelike colors.",
    "Cinematic Realism": "Live-action film aesthetic, dense shadows, controlled highlights, strong tonal separation, convincing material detail.",
    "Soft Pastel Photography": "Fine-art photographic treatment, pale pastel hues, softly diffused illumination, delicate tonal transitions, quiet atmosphere.",
    "Warm Sepia Editorial": "Fashion-magazine finish, amber and brown color grading, feathered shadows, subtle grain, warm luminous highlights.",
    "Instant Film": "Vintage instant-film character, imperfect color response, visible grain, gently faded tones, nostalgic warmth.",
    "Transparent Watercolor": "Watercolor on textured paper, translucent pigment layers, softly spreading edges, delicate variations in color density.",
    "Watercolor and Ink": "Watercolor illustration accented with fluid ink contours, airy washes, irregular pigment pooling, expressive handmade marks.",
    "Watercolor Fashion Illustration": "Fashion illustration in watercolor, graceful ink accents, luminous washes, delicate bleeding pigments, refined painterly detail.",
    "Splattered Watercolor": "Experimental watercolor treatment, scattered pigment droplets, running washes, salt-like mottling, pencil accents on rough paper.",
    "Textured Oil Painting": "Oil-painted canvas, broad expressive strokes, thick pigment deposits, tactile knife-work, richly varied painted surfaces.",
    "Classical Painterly Realism": "Classical oil-painting treatment, carefully modeled forms, warm shadow transitions, rich pigments, restrained brush texture.",
    "Oil Painting × Digital Realism": "Classical painted color relationships combined with precise digital rendering, luminous materials, subtle chiaroscuro, refined surface detail.",
    "Polished Anime Illustration": "Polished anime illustration, precise contours, smoothly modeled shading, carefully finished details, harmonious digital color.",
    "Flat-Shaded Cartoon": "Playful cartoon drawing, simplified forms, solid color fills, minimal tonal modeling, expressive graphic shapes.",
    "Painterly Anime": "Anime-inspired painting, softly brushed color transitions, atmospheric illumination, richly painted textures, illustrative detail.",
    "Minimal Line Drawing": "Economical contour drawing, controlled line weight, simplified details, crisp monochrome strokes, little or no shading.",
    "Coloring-Book Ink": "Coloring-book ink drawing, clearly enclosed shapes, consistent dark outlines, unfilled interiors, easily readable details.",
    "Colored Line Illustration": "Flat graphic illustration with colored outlines, restrained accent hues, simplified fills, a lightly handmade finish.",
    "Photo and Doodle Mixed Media": "Photographic textures combined with hand-drawn doodles, crisp illustrative marks, playful graphic accents, mixed-media finish.",
    "Cyanotype": "Cyanotype print, deep blue pigment, pale unprinted tones, fibrous paper, uneven chemical development.",
    "Impasto Expressionism": "Expressionist impasto, sculpted paint buildup, vigorous knife strokes, exposed canvas grain, emotionally exaggerated color.",
    "Marker Sketch": "Loose marker drawing, uneven ink saturation, lively pen strokes, slight color seepage, spontaneous sketchbook character.",
    "Vintage Pop Print": "Retro pop illustration, dotted print shading, assertive outlines, restricted vivid inks, imperfect screenprinted finish.",
    "Photocopied Zine": "DIY zine treatment, degraded photocopy texture, distressed ink, rough paper surfaces, abrasive monochrome contrast.",
    "Thermal Airbrush": "Airbrushed heat-map aesthetic, smoothly melting colors, radiant pink-to-orange transitions, hazy glow, softly feathered boundaries.",
    "Film Noir": "Classic noir photography, nearly black shadows, stark white highlights, hard-edged illumination, tense monochrome atmosphere.",
    "Futurist Glam": "Futuristic luxury finish, mirrorlike metals, shifting iridescence, immaculate gloss, sharply articulated reflections.",
    "Polished 3D Render": "Refined CGI rendering, carefully shaded materials, dimensional lighting, smooth geometry, convincing surface response.",
    "Clay Animation": "Hand-sculpted modeling clay, softly rounded forms, tactile matte surfaces, playful stop-motion character.",
    "Low-Poly Game Art": "Faceted game artwork, visibly simplified polygon surfaces, angular forms, economical geometry, distinct color planes.",
    "Origami": "Folded-paper sculpture, crisp creases, angular paper planes, subtle paper fibers, handcrafted material detail.",
    "Layered Papercut": "Layered cut-paper artwork, sharply cut edges, tactile cardstock, shallow shadows between paper layers.",
    "Paper Quilling": "Paper-quilling artwork, tightly curled paper strips, delicate coils, ornamental loops, tangible handmade surfaces.",
    "Retro Pixel Art": "Retro pixel artwork, deliberate square-pixel clusters, restricted palette, stepped contours, handcrafted game-sprite shading.",
    "Stained Glass": "Stained-glass artwork, jewel-like translucent colors, dark lead outlines, luminous panes, handcrafted glass texture.",
    "Natural Photorealism": "Photographic realism, believable materials, subtle surface irregularities, coherent reflections and shadows, lifelike color relationships.",
    "Natural Skin Realism": "Lifelike skin with delicate pores, fine facial hairs, subtle tonal variation, softly varying sheen, and small natural imperfections.",
    "Clean Digital Photography": "Contemporary digital photography, crisp yet natural detail, neutral color response, clear tonal separation, carefully preserved highlight and shadow information.",
    "Organic Analog Photography": "Analog photographic character, gently varied grain, nuanced colors, slightly softened microcontrast, subtle imperfections in the photographic finish.",
    "Natural Cinematic": "Live-action film aesthetic, believable available light, restrained grading, nuanced shadows, gently luminous highlights, convincing photographic textures.",
    "Golden-Hour Cinema": "Photorealistic cinema aesthetic, honey-colored backlight, gently glowing edges, cooler shaded areas, delicate atmospheric warmth, restrained grain.",
    "Sunlit Interior Cinema": "Live-action interior aesthetic, sunlight filtering through suspended dust, luminous shafts of light, softly shaded materials, intimate warmth.",
    "Hard-Sun Drama": "Photorealistic dramatic treatment, concentrated sunlight, sharply defined shadows, bright surface reflections, strong tonal contrast, tangible material textures.",
    "Low-Key Cinematic": "Live-action dramatic realism, sparse illumination, rich dark tones, carefully controlled highlights, selective texture visibility, a quiet sense of tension.",
    "Soft Window-Light Cinema": "Photorealistic film aesthetic, broad diffused window light, gradual shadow transitions, delicate surface detail, subtle reflected illumination, calm atmosphere.",
    "Dreamy Cinematic Realism": "Photographic film aesthetic, luminous atmospheric softness, delicate highlight glow, pastel-leaning colors, gently reduced contrast, believable textures beneath the softness.",
    "Warm Editorial Cinema": "Cinematic fashion photography, amber-brown grading, softly feathered shadows, carefully shaped highlights, refined material detail, discreet grain.",
    "Portra-Inspired Natural Film": "Kodak Portra-inspired photographic color, gentle grain, restrained saturation, nuanced skin tones, softly transitioning highlights.",
    "1980s Warm Film": "1980s photographic finish, gently warmed colors, visible analog grain, modest optical softness, nostalgic tonal character.",
    "Cinematic Instant Film": "Instant-film-inspired photography, gently faded color, uneven grain, mellow contrast, warm nostalgia, believable photographic detail.",
    "Warm–Cool Cinematic Grade": "Photorealistic film treatment, warm illuminated tones against cool blue shadows, restrained overall saturation, carefully preserved natural skin color.",
    "Muted Thriller Grade": "Live-action thriller aesthetic, subdued colors, cool gray shadows, dense midtones, restrained highlights, subtle grain, uneasy atmosphere.",
    "Bleach-Bypass-Inspired Cinema": "Bleach-bypass-inspired film treatment, reduced chroma, dense blacks, strong tonal contrast, gritty grain, firmly defined highlights.",
    "Neon-Noir Realism": "Live-action nocturnal realism, localized cyan and magenta illumination, deep neutral shadows, plausible colored reflections, restrained highlight glow.",
    "Black-and-White Cinema": "Monochrome live-action film aesthetic, rich black tones, luminous whites, expressive gray transitions, sculpted illumination, delicate grain.",
    "Everyday Smartphone Snapshot": "Casual smartphone photograph, everyday available light, believable skin texture, neutral color balance, mild sensor noise, ordinary digital sharpness, spontaneous everyday atmosphere.",
    "Shot-on-iPhone Everyday Look": "Photo with an everyday shot-on-iPhone look, natural automatic exposure, lifelike colors, restrained local contrast, visible fine skin texture, modest digital sharpening, casual available-light realism.",
    "Low-Light Phone Snapshot": "Casual low-light smartphone photo, mixed indoor color temperatures, slightly noisy shadows, restrained detail recovery, imperfect white balance, realistic skin, a quietly unpolished digital finish.",
    "Unretouched RAW-Look Photo": "Photographic realism with a minimally processed RAW-like appearance, restrained saturation, gentle tonal contrast, natural skin variation, visible pores and fine lines, subtle sensor texture, realistic material detail.",
    "Instagram Casual Photo Dump": "Casual Instagram photo-dump aesthetic, everyday available lighting, relaxed color balance, subtle digital noise, honest skin texture, lightly processed photographic finish, informal personal-diary mood.",
    "Instagram Direct-Flash Glam": "Social-media street-glamour photography, direct flash illumination, crisp highlight transitions, natural skin texture, fine film-like grain, rich dark tones, a relaxed yet polished nightlife mood.",
    "Instagram Soft Luxury Editorial": "Soft luxury editorial photography, cream and warm neutral colors, luminous diffused lighting, delicate natural shadows, finely resolved fabric, realistic skin detail, restrained glossy finish.",
    "Muted Cafe Lifestyle": "Muted lifestyle photography, oat-beige and subdued brown palette, soft ambient daylight, low color saturation, gently lifted shadows, tactile linen and ceramic textures, calm everyday warmth.",
    "2000s Digicam Flash": "Early-2000s compact digital-camera aesthetic, small-sensor noise, punchy flash highlights, slightly brittle digital detail, vivid casual color, imperfect exposure, nostalgic snapshot finish.",
    "Warm Travel Documentary": "Travel documentary photography, warm natural illumination, subdued sage and ochre colors, gentle contrast, tactile weathered surfaces, fine analog-like grain, a quietly nostalgic photographic finish.",
    "Prestige Sports Documentary": "Prestige documentary photographic treatment, restrained desaturated colors with one subtle accent, sculpted shadow detail, atmospheric light, fine film grain, serious and contemplative mood.",
    "Warm Household Cinema": "Photorealistic domestic cinema, warm tungsten practical lighting, softly graduated shadows, believable household color, natural skin texture, delicate film grain, intimate nostalgic atmosphere.",
    "Luxury Material Photography": "Luxury still-life photographic finish, deep brown and brass-gold palette, warm amber illumination, dense yet readable shadows, tactile leather grain, precise metallic reflections, refined catalog realism.",
    "Tactile Surreal Fashion": "Surreal fashion photography with tangible practical-effects realism, physically convincing surfaces, lifelike skin, controlled clean illumination, organic film texture, uncanny but materially believable finish.",
    "Dramatic Editorial Portrait": "Dramatic editorial photography, richly textured materials, deep earthy colors, carefully shaped light, dense blacks, lifelike skin, a theatrical yet photographic atmosphere.",
    "Humanist Monochrome Fashion": "Humanist black-and-white fashion photography, expressive tonal transitions, honest skin texture, subtle grain, tactile fabrics, restrained retouching, emotionally direct photographic realism.",
    "Hard-Light Monochrome Fashion": "High-contrast monochrome fashion photography, hard sculptural illumination, deep blacks, bright controlled highlights, crisp fabric detail, cool polished editorial intensity.",
    "Painterly Color Photography": "Painterly color photography, subdued amber and crimson accents, soft chromatic transitions, atmospheric moisture, delicate film texture, contemplative urban mood.",
    "Everyday Color Photography": "Everyday color photography, rich red and green accents, ordinary available light, dense analog-like color, understated surface texture, quietly vivid documentary mood.",
    "Intimate Diary Photography": "Intimate diary-style photography, imperfect available lighting, warm color casts, visible grain, truthful skin texture, raw emotional immediacy, personal snapshot finish.",
    "Nolan-Inspired Grounded Thriller": "Photorealistic cinematic treatment inspired by Christopher Nolan, cool restrained colors, dense shadow detail, forceful but believable lighting, fine film texture, grounded material realism, tense atmosphere.",
    "Villeneuve-Inspired Atmospheric Sci-Fi": "Photorealistic atmospheric science-fiction cinema inspired by Denis Villeneuve, restrained earth and steel tones, diffused haze, carefully limited highlights, tactile surfaces, solemn and mysterious mood.",
    "Anderson-Inspired Pastel Cinema": "Photorealistic whimsical cinema inspired by Wes Anderson, coordinated dusty pastels, warm cream and mustard accents, gentle controlled illumination, tactile vintage materials, dry nostalgic charm.",
    "Wong-Inspired Romantic Night Cinema": "Photorealistic romantic night cinema inspired by Wong Kar-wai, deep crimson and green color accents, luminous practical lights, soft highlight bloom, textured film grain, humid melancholic atmosphere.",
    "Fincher-Inspired Controlled Thriller": "Photorealistic psychological-thriller treatment inspired by David Fincher, restrained olive and steel-blue tones, precise low-key lighting, clean shadow detail, subtle surface grime, controlled uneasy atmosphere.",
    "Kubrick-Inspired Unsettling Cinema": "Photorealistic cinema inspired by Stanley Kubrick, clinically controlled artificial light, cool neutral tones with intense color accents, precise material detail, restrained film texture, unsettling emotional distance.",
    "Scott-Inspired Industrial Sci-Fi": "Photorealistic industrial science-fiction cinema inspired by Ridley Scott, smoky volumetric light, wet metallic reflections, weathered surfaces, deep shadows, luminous practical highlights, gritty atmospheric realism.",
    "Lynch-Inspired Uncanny Cinema": "Photorealistic uncanny cinema inspired by David Lynch, rich burgundy and shadowy blue tones, isolated pools of practical light, textured darkness, subtle film grain, dreamlike psychological unease.",
    "Kurosawa-Inspired Monochrome Drama": "Photorealistic black-and-white cinematic drama inspired by Akira Kurosawa, forceful tonal contrast, textured rain and mist, organic grain, rich midtones, rugged material realism, grave emotional weight.",
    "Burton-Inspired Gothic Cinema": "Photorealistic gothic fantasy cinema inspired by Tim Burton, cold blue-gray tones, pale luminous highlights, tactile aged materials, theatrical shadows, eerie whimsical atmosphere, live-action material realism.",
    "Hand-Painted Fantasy Anime": "Hand-drawn 2D fantasy animation, delicate contour lines, softly painted gouache-like environments, restrained cel shadows, natural greens and warm earth colors, tactile brushwork, gentle wonder.",
    "Luminous Contemporary Anime": "Contemporary 2D anime film finish, precise fine linework, luminous atmospheric color, delicate reflected light, painted environmental detail, restrained cel shading, radiant emotional mood.",
    "Psychological Realist Anime": "Hand-drawn 2D psychological anime, naturalistic character rendering, disciplined ink contours, restrained cel shadows, believable painted textures, subtly disquieting colors, mature dramatic tone.",
    "Retro Industrial Cyberpunk Anime": "Late-1980s-inspired 2D cyberpunk animation, meticulous mechanical linework, firm cel-shadow shapes, worn industrial textures, muted urban colors with sharp luminous accents, subtle analog animation grain.",
    "Retro Television Cartoon": "Retro 2D television cartoon, bold clean outlines, economical flat color fills, simplified rounded forms, minimal painted shading, cheerful vintage palette, light paper-like texture.",
    "Traditional Feature Animation": "Traditional hand-drawn 2D feature animation, expressive flowing ink lines, richly painted textures, warm glowing colors, soft layered cel shadows, emotionally vivid storybook atmosphere.",
    "Gritty Rotoscope-Inspired Animation": "Gritty hand-drawn 2D animation, rotoscope-inspired naturalistic forms, rough ink contours, uneven painted textures, earthy muted colors, heavy graphic shadows, adult urban-fantasy atmosphere.",
    "Mid-Century Animation Color Script": "Mid-century animation color-script illustration, matte gouache texture, simplified decorative forms, bold contrasting hues, playful pastel accents, expressive hand-painted color, storybook warmth.",
    "Graphic Angular 2D Animation": "Graphic 2D animation, sharply stylized angular forms, confident clean contours, broad flat color areas, strong graphic shadow shapes, restrained gradients, bold expressive visual economy.",
    "Graphic-Novel Cel-Shaded 2D": "Two-dimensional graphic-novel rendering, decisive ink contours, crisp cel-shadow boundaries, selectively painted skin transitions, vivid slightly weathered colors, sparse ink texture, dramatic drawn highlights.",
    "Slightly Missed Autofocus": "Ordinary phone photo with slightly missed autofocus, gently softened subject detail, recognizable features and believable everyday colors.",
    "Accidental Focus on the Wrong Surface": "Casual photograph with focus accidentally locked onto an incidental surface, leaving the intended subject mildly defocused; otherwise natural processing.",
    "Whole-Image Defocus": "Everyday phone photo with mild overall defocus, gently softened edges throughout, recognizable forms and natural colors, without directional streaking.",
    "Small Hand-Shake Blur": "Quick phone photograph with tiny directional smearing from hand tremor, mostly readable detail, ordinary digital color and everyday light.",
    "Localized Moving-Hand Blur": "Everyday smartphone photograph with slight movement smearing restricted to the moving hands, while stationary surfaces remain comparatively clear; ordinary light and lifelike skin.",
    "Uneven Optical Softness": "Casual digital photograph with subtly uneven optical clarity, a small region softer than the rest, ordinary contrast and imperfect color balance, a plainly unpolished finish.",
    "Low-Light Phone Noise": "Low-light phone photograph with fine luminance noise and faint colored shadow speckles, modest detail retention, natural skin variation, believable consumer-camera processing.",
    "Fluorescent Color Cast": "Casual indoor phone photograph under utilitarian fluorescent lighting, a faint yellow-green cast, honest skin texture, mild digital noise, ordinary uncorrected color.",
    "Patchy Overexposure": "Ordinary phone snapshot with uneven illumination and a few locally washed-out highlights, less detail in the brightest surfaces, natural remaining colors, a mildly imperfect exposure.",
    "Clumsy Phone Flash": "Casual phone-flash photograph, abruptly bright skin and fabric highlights, much dimmer ambient surroundings, uneven tonal balance, a blunt everyday digital finish.",
    "Mixed-Light White-Balance Error": "Everyday indoor photo with mixed warm and cool illumination, imperfect automatic white balance and slightly inconsistent neutral colors.",
    "Limited Shadow Detail": "Ordinary digital snapshot with reduced tonal information in dark areas, slightly blocked-up shadow textures, readable brighter surfaces, natural color and restrained processing.",
    "Shared-Photo JPEG Texture": "Everyday photo with the finish of a lightly recompressed social-media JPEG, subtle loss of fine texture, faint compression roughness around hard edges, otherwise convincing photographic detail.",
    "Fingerprint-Smudged Lens": "Phone photograph through a lightly fingerprint-smudged lens, localized milky flare around bright lights, slightly reduced contrast in affected areas, otherwise ordinary photographic texture.",
    "Raindrops on Phone Lens": "Rainy-day phone photograph with a few droplets on the lens causing small irregular soft patches and localized light scattering, recognizable scene detail elsewhere.",
    "Imperfect Mirror Surface": "Everyday mirror photograph with faint wipe streaks and small smudges on the glass, ordinary household illumination, believable reflected detail, a casually unclean photographic finish.",
    "Honest Skin Without Glamour Retouch": "Natural photographic skin with small irregular pores, fine lines, uneven pigmentation and a restrained oily sheen; believable light response and lightly processed everyday detail.",
    "Clear Everyday Amateur Photo": "Everyday amateur photography, ordinary household light, plainly rendered fabric and skin, unremarkable colors, legible environmental textures, a personal family-album finish.",
    "Accidental Phone Snapshot — Balanced": "Unremarkable everyday phone snapshot, faint motion softness, uneven available light, a few overly bright patches, believable skin and ordinary colors, casually processed and unpolished.",
    "Dim Event Snapshot — Balanced": "Casual low-light event photograph, modest sensor noise, bright practical lights blooming slightly, mildly inconsistent focus, believable smartphone color processing and natural skin texture."
}

# Browsing groups only: categories never add or override prompt instructions.
STYLE_CATEGORIES = {
    "Photorealistic": [
        "Natural Photography", "Natural Photorealism", "Natural Skin Realism",
        "Clean Digital Photography", "Organic Analog Photography",
        "Soft Pastel Photography", "Warm Sepia Editorial",
    ],
    "Cinematic": [
        "Cinematic Realism", "Natural Cinematic", "Golden-Hour Cinema",
        "Sunlit Interior Cinema", "Hard-Sun Drama", "Low-Key Cinematic",
        "Soft Window-Light Cinema", "Dreamy Cinematic Realism", "Warm Editorial Cinema", "Film Noir",
    ],
    "Illustration": [
        "Polished Anime Illustration", "Flat-Shaded Cartoon", "Painterly Anime",
        "Minimal Line Drawing", "Coloring-Book Ink", "Colored Line Illustration",
        "Marker Sketch", "Thermal Airbrush", "Retro Pixel Art",
    ],
    "Painting": [
        "Transparent Watercolor", "Watercolor and Ink", "Watercolor Fashion Illustration",
        "Splattered Watercolor", "Textured Oil Painting", "Classical Painterly Realism",
        "Impasto Expressionism",
    ],
    "3D Rendering": ["Polished 3D Render", "Low-Poly Game Art", "Futurist Glam"],
    "Craft & Materials": ["Clay Animation", "Origami", "Layered Papercut", "Paper Quilling", "Stained Glass"],
    "Print & Experimental": ["Cyanotype", "Vintage Pop Print", "Photocopied Zine"],
    "Film & Color Grading": [
        "Instant Film", "Portra-Inspired Natural Film", "1980s Warm Film", "Cinematic Instant Film",
        "Warm–Cool Cinematic Grade", "Muted Thriller Grade", "Bleach-Bypass-Inspired Cinema",
        "Neon-Noir Realism", "Black-and-White Cinema",
    ],
    "Mixed Media": ["Oil Painting × Digital Realism", "Photo and Doodle Mixed Media"],
    "Smartphone & Social Photography": [
        "Everyday Smartphone Snapshot", "Shot-on-iPhone Everyday Look", "Low-Light Phone Snapshot",
        "Unretouched RAW-Look Photo", "Instagram Casual Photo Dump", "Instagram Direct-Flash Glam",
        "Instagram Soft Luxury Editorial", "Muted Cafe Lifestyle", "2000s Digicam Flash",
    ],
    "Editorial & Documentary Photography": [
        "Warm Travel Documentary", "Prestige Sports Documentary", "Warm Household Cinema",
        "Luxury Material Photography", "Tactile Surreal Fashion", "Dramatic Editorial Portrait",
        "Humanist Monochrome Fashion", "Hard-Light Monochrome Fashion", "Painterly Color Photography",
        "Everyday Color Photography", "Intimate Diary Photography",
    ],
    "Director-Inspired Cinema": [
        "Nolan-Inspired Grounded Thriller", "Villeneuve-Inspired Atmospheric Sci-Fi",
        "Anderson-Inspired Pastel Cinema", "Wong-Inspired Romantic Night Cinema",
        "Fincher-Inspired Controlled Thriller", "Kubrick-Inspired Unsettling Cinema",
        "Scott-Inspired Industrial Sci-Fi", "Lynch-Inspired Uncanny Cinema",
        "Kurosawa-Inspired Monochrome Drama", "Burton-Inspired Gothic Cinema",
    ],
    "2D Animation": [
        "Hand-Painted Fantasy Anime", "Luminous Contemporary Anime", "Psychological Realist Anime",
        "Retro Industrial Cyberpunk Anime", "Retro Television Cartoon", "Traditional Feature Animation",
        "Gritty Rotoscope-Inspired Animation", "Mid-Century Animation Color Script",
        "Graphic Angular 2D Animation", "Graphic-Novel Cel-Shaded 2D",
    ],
    "Focus & Motion Imperfections": [
        "Slightly Missed Autofocus", "Accidental Focus on the Wrong Surface",
        "Whole-Image Defocus", "Small Hand-Shake Blur", "Localized Moving-Hand Blur",
        "Uneven Optical Softness",
    ],
    "Exposure & Color Imperfections": [
        "Low-Light Phone Noise", "Fluorescent Color Cast", "Patchy Overexposure",
        "Clumsy Phone Flash", "Mixed-Light White-Balance Error", "Limited Shadow Detail",
    ],
    "Lens, Compression & Mirror": [
        "Shared-Photo JPEG Texture", "Fingerprint-Smudged Lens",
        "Raindrops on Phone Lens", "Imperfect Mirror Surface",
    ],
    "Natural Amateur Photography": [
        "Honest Skin Without Glamour Retouch", "Clear Everyday Amateur Photo",
        "Accidental Phone Snapshot — Balanced", "Dim Event Snapshot — Balanced",
    ],
}
